name: Nightly Build

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev nlohmann-json3-dev valgrind

    - name: Build with debug info
      run: |
        make debug

    - name: Run memory check
      run: |
        valgrind --leak-check=full --error-exitcode=1 ./weather-cli-debug --help || true

    - name: Upload nightly build
      uses: actions/upload-artifact@v3
      with:
        name: weather-cli-nightly
        path: weather-cli-debug
        retention-days: 7
